enabled: {{ .Requirements.ingress.externalDNS }}
sources:
- ingress
provider: google
google:
  serviceAccountSecret: external-dns-gcp-sa
rbac:
  create: true
domainFilters:
- "{{ .Requirements.ingress.domain }}"
certs:
  image: gcr.io/jenkinsxio/builder-go:
  imageTag: 2.0.987-319
